import os

epilog = """
\033[36m
Bacterial-rnaseq-preprocessing: A Snakemake workflow
for the preprocessing of short read RNAseq data in bacteria.
---
Max Planck Unit for the Science of Pathogens. Copyright (c) 2025.
\033[0m
"""


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/coverage.smk"
include: "rules/dedup.smk"
include: "rules/mapping.smk"
include: "rules/qc.smk"
include: "rules/quantification.smk"
include: "rules/trim.smk"


onstart:
    print("\n--- Analysis started ---\n")
    print(f"RNAseq samples: {list(samples.index)}\n\n")


onsuccess:
    print("\n--- Workflow finished successfully! ---\n")
    print(epilog)


onerror:
    print("\n--- An error occurred, see the snakemake log ---\n")
    print(epilog)


# target rules
# -----------------------------------------------------
rule all:
    input:
        get_final_output(),
