report_header_info:
  - Contact E-mail: "bioinformatics@mpusp.mpg.de"
  - Application Type: "Bacterial RNAseq"
  - Sequencing Platform: "Illumina"
  - Sequencing Setup: "Total RNAseq"

title: "Bacterial RNAseq processing"
subtitle: "A Snakemake workflow for the analysis of RNAseq data in bacteria."
intro_text: ""

show_analysis_paths: false

custom_logo: "../resources/images/MPUSP_logo.png"
custom_logo_url: "https://www.mpusp.mpg.de/"
custom_logo_title: "Max Planck Unit for the Science of Pathogens"

skip_versions_section: false
disable_version_detection: true
versions_table_group_header: "Workflow Analysis Steps"

skip_generalstats: true

remove_sections:
  - samtools-stats

module_order:
  - star
  - cutadapt
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*/clipped_reads/*_fastqc.zip"
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*/raw_reads/*_fastqc.zip"

report_section_order:
  fastqc_raw:
    before: fastqc_trimmed
